### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#17]
Let's a list of TODOs in a single place rather with tons of issues.

Apis
- [x] capacitive buttons events / pressed apis
- [x] finalize pin mapping in board definition
- [ ] generate API docs

Art
- [x] logo svg based
- [x] avatar image (svg)
- [x] loader image (svg)
- [ ] review category colors

Docs
- [ ] getting started
- [ ] generate api docs (once finalized)
- [ ] add 'Beta' somewhere on the page or in the domain name
